"""create nodes table

Revision ID: 75f4b7372dbf
Revises: 092b8d89dbbd
Create Date: 2026-07-23 06:11:17.108652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75f4b7372dbf'
down_revision: Union[str, Sequence[str], None] = '092b8d89dbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('todo_state', sa.String(length=12), nullable=True),
    sa.Column('priority', sa.String(length=1), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repeat_rule', sa.String(length=4), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vec', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(body, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nodes_body_trgm', 'nodes', ['body'], unique=False, postgresql_using='gin', postgresql_ops={'body': 'gin_trgm_ops'})
    op.create_index('ix_nodes_deadline', 'nodes', ['deadline_at'], unique=False, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('ix_nodes_kind_state', 'nodes', ['kind', 'todo_state'], unique=False)
    op.create_index('ix_nodes_parent', 'nodes', ['parent_id'], unique=False)
    op.create_index('ix_nodes_remind', 'nodes', ['remind_at'], unique=False, postgresql_where=sa.text('archived_at IS NULL AND notified_at IS NULL'))
    op.create_index('ix_nodes_scheduled', 'nodes', ['scheduled_at'], unique=False, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('ix_nodes_search', 'nodes', ['search_vec'], unique=False, postgresql_using='gin')
    op.create_index('ix_nodes_title_trgm', 'nodes', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_table('node_tags',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'tag_id')
    )
    op.create_table('pomodoro_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pomo_node', 'pomodoro_sessions', ['node_id'], unique=False)
    op.create_index('ix_pomo_started', 'pomodoro_sessions', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pomo_started', table_name='pomodoro_sessions')
    op.drop_index('ix_pomo_node', table_name='pomodoro_sessions')
    op.drop_table('pomodoro_sessions')
    op.drop_table('node_tags')
    op.drop_table('weekly_reviews')
    op.drop_table('tags')
    op.drop_table('settings')
    op.drop_index('ix_nodes_title_trgm', table_name='nodes', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_nodes_search', table_name='nodes', postgresql_using='gin')
    op.drop_index('ix_nodes_scheduled', table_name='nodes', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index('ix_nodes_remind', table_name='nodes', postgresql_where=sa.text('archived_at IS NULL AND notified_at IS NULL'))
    op.drop_index('ix_nodes_parent', table_name='nodes')
    op.drop_index('ix_nodes_kind_state', table_name='nodes')
    op.drop_index('ix_nodes_deadline', table_name='nodes', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index('ix_nodes_body_trgm', table_name='nodes', postgresql_using='gin', postgresql_ops={'body': 'gin_trgm_ops'})
    op.drop_table('nodes')
    # ### end Alembic commands ###
